language: php

php:
  - 7.2
  - 7.3

env:
  matrix:
    - LARAVEL=5.6.*
    - LARAVEL=5.7.*
    - LARAVEL=5.8.*
    - LARAVEL=dev-master

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: LARAVEL=5.6.*
    - php: 7.1
      env: LARAVEL=5.7.*
    - php: 7.1
      env: LARAVEL=5.8.*
    - php: 7.1
  allow_failures:
    - env: LARAVEL=dev-master

sudo: false

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - composer require "illuminate/contracts=${LARAVEL}" --dev --prefer-dist --no-interaction --no-suggest
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script: vendor/bin/phpunit --verbose
